name: toposort
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - arrow-cpp=8.0.0=py37hbd6f097_1
  - attrs=22.1.0=py37haa95532_0
  - aws-c-common=0.4.57=ha925a31_1
  - aws-c-event-stream=0.1.6=hd77b12b_5
  - aws-checksums=0.1.9=ha925a31_0
  - aws-sdk-cpp=1.8.185=hd77b12b_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost-cpp=1.73.0=h2bbff1b_12
  - bottleneck=1.3.5=py37h080aedc_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - c-ares=1.19.0=h2bbff1b_0
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py37haa95532_0
  - cffi=1.15.1=py37h2bbff1b_3
  - cftime=1.5.1.1=py37h080aedc_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.6=py37haa95532_0
  - colorcet=3.0.1=py_0
  - cryptography=39.0.1=py37h21b164f_0
  - curl=7.88.1=h2bbff1b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py37h2bbff1b_0
  - dask=2021.10.0=pyhd3eb1b0_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - datashader=0.14.4=py_0
  - datashape=0.5.4=py37haa95532_1
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2021.10.0=py37haa95532_0
  - entrypoints=0.4=py37haa95532_0
  - fastparquet=0.5.0=py37h080aedc_2
  - fftw=3.3.9=h2bbff1b_1
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - fsspec=2022.11.0=py37haa95532_0
  - geos=3.10.2=h39d44d4_0
  - gflags=2.2.2=ha925a31_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - glog=0.5.0=hd77b12b_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdbscan=0.8.28=py37hec80d1f_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.6=h1756f20_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.15.4=py_0
  - holoviz=0.13.0=py_0
  - hvplot=0.8.3=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py37haa95532_0
  - importlib-metadata=4.11.3=py37haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.15.2=py37haa95532_0
  - ipython=7.31.1=py37haa95532_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py37haa95532_1
  - jinja2=3.1.2=py37haa95532_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h2bbff1b_1
  - jsonschema=4.17.3=py37haa95532_0
  - jupyter_client=7.4.9=py37haa95532_0
  - jupyter_core=4.11.2=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.4.4=py37hd77b12b_0
  - krb5=1.19.4=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libboost=1.73.0=h6c2663c_12
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcurl=7.88.1=h86230a5_0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - libnetcdf=4.8.1=h6685c40_2
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.10.0=hcd4344a_0
  - libthrift=0.15.0=he1d8c1a_0
  - libtiff=4.5.0=h6c2663c_2
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.10.3=h0ad7f3c_0
  - libxslt=1.1.37=h2bbff1b_0
  - libzip=1.8.0=h49b8836_0
  - llvmlite=0.39.1=py37h23ce68f_0
  - locket=1.0.0=py37haa95532_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.4.1=py37haa95532_0
  - markupsafe=2.1.1=py37h2bbff1b_0
  - matplotlib=3.5.3=py37h03978a9_2
  - matplotlib-base=3.5.3=py37hd77b12b_0
  - matplotlib-inline=0.1.6=py37haa95532_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - msgpack-python=1.0.3=py37h59b6b97_0
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py37_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py37haa95532_0
  - nbconvert=6.4.1=py37haa95532_0
  - nbformat=5.7.0=py37haa95532_0
  - nest-asyncio=1.5.6=py37haa95532_0
  - netcdf4=1.6.2=py37hda396d2_0
  - notebook=6.4.12=py37haa95532_0
  - numba=0.56.4=py37hf11a4ad_0
  - numexpr=2.8.4=py37h5b0cc5e_0
  - numpy=1.21.5=py37h7a0a035_3
  - numpy-base=1.21.5=py37hca35cd5_3
  - openssl=1.1.1t=h2bbff1b_0
  - packaging=22.0=py37haa95532_0
  - pandas=1.3.5=py37h6214cd6_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.14.4=py_0
  - param=1.13.0=py_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py37hd77b12b_0
  - pip=22.3.1=py37haa95532_0
  - pkgutil-resolve-name=1.3.10=py37haa95532_0
  - plotly=5.14.1=pyhd8ed1ab_0
  - ply=3.11=py37_0
  - prometheus_client=0.14.1=py37haa95532_0
  - prompt-toolkit=3.0.36=py37haa95532_0
  - psutil=5.9.0=py37h2bbff1b_0
  - pyarrow=8.0.0=py37h953b917_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py_0
  - pyct-core=0.5.0=py_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pynndescent=0.5.10=pyh1a96a4e_0
  - pyopenssl=23.0.0=py37haa95532_0
  - pyparsing=3.0.9=py37haa95532_0
  - pyqt=5.15.7=py37hd77b12b_0
  - pyqt5-sip=12.11.0=py37hd77b12b_0
  - pyrsistent=0.18.0=py37h196d8e1_0
  - pysocks=1.7.1=py37_1
  - python=3.7.16=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py37haa95532_0
  - python-snappy=0.6.1=py37hd77b12b_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.7=py37haa95532_0
  - pyviz_comms=2.2.1=py_0
  - pywin32=305=py37h2bbff1b_0
  - pywinpty=2.0.10=py37h5da7b33_0
  - pyyaml=6.0=py37h2bbff1b_1
  - pyzmq=23.2.0=py37hd77b12b_0
  - qt-main=5.15.2=he8e5bd7_8
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h2bbfb41_5
  - re2=2022.04.01=hd77b12b_0
  - requests=2.28.1=py37haa95532_0
  - retrying=1.3.3=py37_2
  - rise=5.7.1=py37haa95532_0
  - scikit-learn=1.0.2=py37hcabfae0_0
  - scipy=1.7.3=py37h7a0a035_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py37haa95532_0
  - shapely=1.8.1=py37h40d3a78_0
  - sip=6.6.2=py37hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - spatialpandas=0.4.7=py_0
  - sqlite=3.41.2=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.17.1=py37haa95532_0
  - testpath=0.6.0=py37haa95532_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - thrift=0.17.0=py37hd77b12b_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py37haa95532_0
  - tornado=6.2=py37h2bbff1b_0
  - tqdm=4.64.1=py37haa95532_0
  - traitlets=5.7.1=py37haa95532_0
  - typing-extensions=4.4.0=py37haa95532_0
  - typing_extensions=4.4.0=py37haa95532_0
  - umap-learn=0.5.3=py37h03978a9_0
  - urllib3=1.26.14=py37haa95532_0
  - utf8proc=2.6.1=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.38.4=py37haa95532_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - xarray=0.20.1=pyhd3eb1b0_1
  - xz=5.2.10=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=hd77b12b_0
  - zict=2.1.0=py37haa95532_0
  - zipp=3.11.0=py37haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - qtpy==2.3.1
prefix: C:\Users\Dell\Documents\Neurociencias\Anaconda\envs\toposort
